# Generated by Django 5.2.8 on 2025-12-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonjob',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
