# Generated by Django 6.0 on 2025-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonjob',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comparisonjob',
            name='xsd_file',
            field=models.FileField(blank=True, null=True, upload_to='schemas/'),
        ),
    ]
